### ISSUE TITLE
HTML special characters

### ISSUE THREAD

**Issue by martoio** [tyrasztt/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/
The ampersand should be written as:
``&amp;``
(Make sure you don't forget the ``;`` at the end)
https://github.com/tyrasztt/prj-rev-bwfs-dasmoto/blob/a3b29e33de92af98cd284d65f5270e22a9c19367/DasmotoProj/index.html#L12

**Comment by tyrasztt** [comment]
I see that I didn't see that I was supposed to put the semi-colon at the end. Thanks for the info.
